### PR TITLE
Support new install mechanism in nb 4.2

### LINKED ISSUE #34: Support new nbextension installation on 4.2
Beta is out:

https://groups.google.com/forum/#!topic/jupyter/RTdb1_k7l0A

Doc on what to do:

https://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html

Make sure we retain compatibility with 4.1 and lower. Will need two sets of instructions in the README. Should also make the 4.1 install/activate automation a bit less brittle when accidentally run under 4.2. (Blows up with nasty exceptions because the base classes we override have changed.)

xref: jupyter-incubator/dashboards#215,  jupyter-incubator/dashboards_bundlers#28, jupyter-incubator/declarativewidgets#304

### PR DESCRIPTION
**Pull request by parente**
Fixes #34

### CODE REVIEW

**Comment by parente** [comment]
@Carreau @minrk everything working fine w/ beta. Will do dashboards next but I expect no problems.

**Comment by minrk** [comment]
That's great! I'm working on the same for ipyparallel.

**Comment by Carreau** [comment]
We should draft out a blog post will all the recent & soon to be releases.

**Comment by minrk** [comment]
@Carreau I started one a little bit ago, if you would like to have a look at it.

**Pull request merged**
